# Generated by Django 5.2.15 on 2026-07-01 02:02

import core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('cnpj', models.CharField(max_length=14, unique=True, validators=[core.validators.validate_cnpj])),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('zip_code', models.CharField(max_length=9)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owners', models.ManyToManyField(blank=True, related_name='owned_studios', to=settings.AUTH_USER_MODEL)),
                ('staffs', models.ManyToManyField(blank=True, related_name='staff_studios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'estúdio',
                'verbose_name_plural': 'estúdios',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StudioApprovalRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studio_approval_requests', to=settings.AUTH_USER_MODEL)),
                ('studio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval_request', to='studios.studio')),
            ],
            options={
                'verbose_name': 'solicitação de aprovação',
                'verbose_name_plural': 'solicitações de aprovação',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TattooArtist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('bio', models.TextField(blank=True)),
                ('instagram', models.CharField(blank=True, max_length=100)),
                ('specialties', models.CharField(blank=True, max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artists', to='studios.studio')),
            ],
            options={
                'verbose_name': 'tatuador',
                'verbose_name_plural': 'tatuadores',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(upload_to='portfolios/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to='studios.tattooartist')),
            ],
            options={
                'verbose_name': 'item de portfólio',
                'verbose_name_plural': 'itens de portfólio',
                'ordering': ['-created_at'],
            },
        ),
    ]
