# Generated by Django 5.2.15 on 2026-07-02 23:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('reference_image', models.ImageField(blank=True, null=True, upload_to='budgets/')),
                ('status', models.CharField(choices=[('sent', 'Enviado'), ('in_analysis', 'Em análise'), ('answered', 'Respondido')], default='sent', max_length=20)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_requests', to='studios.tattooartist')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_requests', to=settings.AUTH_USER_MODEL)),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_requests', to='studios.studio')),
            ],
            options={
                'verbose_name': 'solicitação de orçamento',
                'verbose_name_plural': 'solicitações de orçamento',
                'ordering': ['-created_at'],
            },
        ),
    ]
